//  MainViewController.swift
//  The one place a plugin written in this app gets registered.
//
//  Capacitor does NOT find a plugin by looking for it. registerPlugins() in
//  CapacitorBridge reads capacitor.config.json's `packageClassList` and
//  registers exactly what is named there -- and that list is generated by
//  `npx cap sync` from the npm packages installed, so a plugin that lives in
//  this app rather than in a package is in it never:
//
//      "packageClassList": []
//
//  LinguaSharePlugin was written, compiled, signed and shipped in three
//  builds without ever being registered. Nothing said so. The JS asked
//  Capacitor for it, got nothing back, and -- written to stay quiet when
//  there was nobody to tell -- stayed quiet, while the keyboard on the phone
//  answered "draw some letters first" with the letters drawn.
//
//  capacitorDidLoad() is the hook that exists for this. It runs while the
//  bridge is being built, before the web view has asked for anything.

import UIKit
import Capacitor

class MainViewController: CAPBridgeViewController {
  override func capacitorDidLoad() {
    bridge?.registerPluginInstance(LinguaSharePlugin())
  }
}
