//  MainViewController.swift
//  The one place a plugin written in this app gets registered.
//
//  Capacitor does NOT find a plugin by looking for it. registerPlugins() in
//  CapacitorBridge reads capacitor.config.json's `packageClassList` and
//  registers exactly what is named there -- and that list is generated by
//  `npx cap sync` from the npm packages installed, so a plugin that lives in
//  this app rather than in a package is in it never:
//
//      "packageClassList": []
//
//  LinguaSharePlugin was written, compiled, signed and shipped in three
//  builds without ever being registered. Nothing said so. The JS asked
//  Capacitor for it, got nothing back, and -- written to stay quiet when
//  there was nobody to tell -- stayed quiet, while the keyboard on the phone
//  answered "draw some letters first" with the letters drawn.
//
//  capacitorDidLoad() is the hook that exists for this. It runs while the
//  bridge is being built, before the web view has asked for anything.

import UIKit
import Capacitor

class MainViewController: CAPBridgeViewController {
  override func capacitorDidLoad() {
    bridge?.registerPluginInstance(LinguaSharePlugin())
    bridge?.registerPluginInstance(LinguaPlanPlugin())
    /* Registered rather than called: nothing in www/ asks it anything yet.
       It is here because load() is where its Transaction.updates listener
       starts, and a renewal that arrives while nothing is listening is a day
       the app is wrong about. See the head of LinguaStore.swift. */
    bridge?.registerPluginInstance(LinguaStorePlugin())
    // And the plan itself, as a script rather than as an answer to a call:
    // what a free plan looks like is decided on the first frame, and a call
    // comes back after it. See the head of LinguaPlan.swift.
    LinguaPlanPlugin.inject(into: bridge?.webView)
  }
}
