//  MainViewController.swift
//  The one place a plugin written in this app gets registered.
//
//  Capacitor does NOT find a plugin by looking for it. registerPlugins() in
//  CapacitorBridge reads capacitor.config.json's `packageClassList` and
//  registers exactly what is named there -- and that list is generated by
//  `npx cap sync` from the npm packages installed, so a plugin that lives in
//  this app rather than in a package is in it never:
//
//      "packageClassList": []
//
//  LinguaSharePlugin was written, compiled, signed and shipped in three
//  builds without ever being registered. Nothing said so. The JS asked
//  Capacitor for it, got nothing back, and -- written to stay quiet when
//  there was nobody to tell -- stayed quiet, while the keyboard on the phone
//  answered "draw some letters first" with the letters drawn.
//
//  capacitorDidLoad() is the hook that exists for this. It runs while the
//  bridge is being built, before the web view has asked for anything.

import UIKit
import Capacitor
import ObjectiveC

class MainViewController: CAPBridgeViewController {
  override func capacitorDidLoad() {
    bridge?.registerPluginInstance(LinguaSharePlugin())
    /* www/store.js asks it on every launch, and registering it here is also
       what starts its Transaction.updates listener in load() -- a renewal
       that arrives while nothing is listening is a day the app is wrong
       about. See the head of LinguaStore.swift. */
    bridge?.registerPluginInstance(LinguaStorePlugin())
    /* Registered here like the others, and for one reason on top of
       being reachable: load() is where it picks up a notification tapped
       from a cold launch, which AppDelegate has been holding since before
       there was a bridge. See the head of LinguaPush.swift. */
    bridge?.registerPluginInstance(LinguaPushPlugin())
    /* And the bar iOS puts over the keyboard. prepareWebView() has already
       made the WKWebView by the time this runs (CAPBridgeViewController's
       loadView(), a few lines above the capacitorDidLoad() call), so WebKit
       is loaded and the class below is registered. */
    hideFormAccessoryBar()
    keepStill()
  }

  /* ---- THE SCREEN IS WHAT IS ABOVE THE KEYBOARD ----------------------------
     「投稿画面のガタガタがウザすぎる」「ガタガタするのはキーボードが出た後に
     画面を上下に早く揺らした時なんだよな」 OWNER 2026-09-25 (docs/
     FEATURE_RULES.md, 2026-09-25 投稿の画面は揺れない).

     WebKit's own answer to a keyboard is to leave the web view the size it
     was, lay the keyboard over it, give the page's scroll view room at the
     foot as tall as the keyboard, and scroll the page up to show the field.
     That room is what a finger shaking the screen moves through, and the page
     was chasing it from JavaScript one event behind -- which is the shaking.

     So WebKit is not told about the keyboard at all: the four notifications
     it listens for are taken off it, the same thing @capacitor/keyboard does
     for its `native` resize. What it is given instead is a smaller view --
     this view's foot is set to the top of the keyboard, in the keyboard's own
     animation -- so what the page can see IS the screen, there is no room at
     the foot to scroll into, and nothing is left for anybody to chase.
     `removeObserver` and a frame are public API; nothing private is touched.

     The root view of this controller IS the WKWebView (CAPBridgeViewController
     .loadView, `view = webView`), so it is that view's frame. The window lays
     its root view out to its own bounds again on a turn of the phone, so
     viewDidLayoutSubviews puts the foot back where the keyboard says.

     Only a keyboard along the foot counts. One that stops short of the bottom
     -- an iPad's floating one -- covers no strip of the page to give up. */
  private var kbCover: CGFloat = 0

  private func keepStill() {
    guard let web = webView else { return }
    let nc = NotificationCenter.default
    for name in [UIResponder.keyboardWillShowNotification,
                 UIResponder.keyboardWillHideNotification,
                 UIResponder.keyboardWillChangeFrameNotification,
                 UIResponder.keyboardDidChangeFrameNotification] {
      nc.removeObserver(web, name: name, object: nil)
    }
    /* Capacitor already turns the bounce off (CAPBridgeViewController,
       `bounces = false`); said again here because this is the one place that
       says the page does not move. */
    web.scrollView.bounces = false
    web.scrollView.alwaysBounceVertical = false
    nc.addObserver(self, selector: #selector(kbMove(_:)),
                   name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
    nc.addObserver(self, selector: #selector(kbMove(_:)),
                   name: UIResponder.keyboardWillHideNotification, object: nil)
  }

  @objc private func kbMove(_ note: Notification) {
    guard let win = view.window, let info = note.userInfo else { return }
    var cover: CGFloat = 0
    if note.name != UIResponder.keyboardWillHideNotification,
       let end = (info[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
      let r = win.screen.coordinateSpace.convert(end, to: win.coordinateSpace)
      if r.intersects(win.bounds) && r.maxY >= win.bounds.maxY - 1 {
        cover = max(0, win.bounds.maxY - r.minY)
      }
    }
    if cover == kbCover { return }
    kbCover = cover
    let dur = (info[UIResponder.keyboardAnimationDurationUserInfoKey] as? Double) ?? 0.25
    let curve = (info[UIResponder.keyboardAnimationCurveUserInfoKey] as? UInt) ?? 7
    UIView.animate(withDuration: dur, delay: 0,
                   options: [UIView.AnimationOptions(rawValue: curve << 16), .beginFromCurrentState],
                   animations: { self.kbFit() })
  }

  private func kbFit() {
    guard let win = view.window else { return }
    var f = win.bounds
    f.size.height = max(0, win.bounds.height - kbCover)
    if view.frame != f { view.frame = f }
  }

  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    kbFit()
  }

  /* The `∧ ∨ ✓` strip over the keyboard. 「チェック▼▲みたいなところはいらない
     から消して。」「あとカメラとかマイクのやつはキーボードの上に絶対に貼り付けて
     くれ。」OWNER 2026-08-26 -- and those are one fix, not two. The row of
     tools is the foot of the web view, and the web view ends where the
     keyboard starts (keepStill above) -- which is the top of this strip while
     it is there. Take the strip away and the row lands on the keys.

     **There is no public way to do this and it is worth saying so plainly.**
     The strip is not ours -- it is nothing in the app's HTML or CSS. It is the
     inputAccessoryView of the view WebKit puts inside a WKWebView, and the
     property is read-only. What is checked:

       - Capacitor 8 has no setting for it. `accessory` appears nowhere in
         @capacitor/ios; the one keyboard flag it does carry
         (keyboardShouldRequireUserInteraction) is about programmatic focus.
       - @capacitor/keyboard's setAccessoryBarVisible() is not available: this
         app installs @capacitor/core and @capacitor/ios only.
       - UIWebView's inputAssistantItem governs the iPad shortcuts bar and not
         this.

     So this replaces the implementation of `inputAccessoryView` -- a PUBLIC
     property, declared on UIResponder -- on a PRIVATE class, WKContentView.
     That is exactly what @capacitor/keyboard does (Keyboard.m,
     setHideFormAccessoryBar:) and has done in the App Store for years; this
     is that code with the dead UIWebBrowserView half dropped.

     Taking that road at all is an owner decision and this is where it came
     from: 「真似よう。ダメなら諦める」OWNER 2026-08-27 -- match the shipping
     implementation, and if Apple refuses it, stop. **The second half is as
     much the decision as the first: a rejection here is not a puzzle for a
     later session to solve.** The strip stays and nobody looks for another
     way.

     **One thing is deliberately NOT copied.** The plugin assembles the class
     name as ["WK","Content","View"].joined() so the string is not in the
     binary. The name is written out here. Hiding it changes nothing about
     what runs and everything about what it looks like, and this repo does not
     get to be the one that disguises what it is doing. If that is not
     acceptable, the answer is to remove this function, not to obfuscate it.
     Somebody who has decided they can live with being refused has no reason
     to hide anything from the people doing the refusing.

     It fails visibly rather than quietly: if Apple renames or removes the
     class, the guard falls through and the strip is on the screen, which is
     the state somebody is looking at today. There is nothing to be silently
     wrong about.

     What it costs: `✓` is also Done, which blurs the field. On the composer
     that already does nothing -- pwKeepKb() in www/post.js puts the focus
     straight back, which is 「キーボードが下ろせる」being answered. Everywhere
     else the keyboard goes down by touching off the field, as it does in
     every other web view. */
  private func hideFormAccessoryBar() {
    guard let contentView = NSClassFromString("WKContentView"),
          let getter = class_getInstanceMethod(contentView,
                                               NSSelectorFromString("inputAccessoryView"))
    else { return }
    let noBar: @convention(block) (AnyObject) -> UIView? = { _ in nil }
    _ = method_setImplementation(getter, imp_implementationWithBlock(noBar))
  }
}
